### PR TITLE
vision: remove camera cap check and unused speak capability

### LINKED ISSUE #462: Vision often wrongly says image too dark/ camera cap on

### PR DESCRIPTION
**Pull request by jaagut**
# Summary

Removes redundant camera cap check in vision

## Proposed changes

As the camera cover/cap check has been implemented in the camera driver with proper diagnostics, this check in the vision became redundant.
This PR removes the vision check and the speak capability, as it has no use anymore.

## Related issues

Closes #462
#455

## Checklist

- [ ] Run `colcon build`
- [ ] Write documentation
- [ ] Test on your machine
- [ ] Test on the robot
- [ ] Create issues for future work
- [X] Triage this PR and label it

### CODE REVIEW

**Comment by Flova** [comment]
I still think that the audio warning is nice. Even if the functionality is now located in the basler driver. We should debug either way why the audio is not played during startup.

**Comment by jaagut** [comment]
If I remember correctly, we now have a simpler function in misc to speak. We should use that one instead. And I agree, we should speak this warning. However, I don't think it should be located in this vision anymore.

**Comment by Flova** [comment]
> function in misc

I don't know what you mean. There is a simple factory for the speak messages, but it is barely needed and only python (the basler driver is cpp).

**Review by Flova — APPROVED** [review]

**Comment by jaagut** [comment]
Yes, that's the one I meant. And yes, its only for python nodes...

My preference for which node should say the warning:

1. Gameready-script
2. Something in Misc
3. Vision
4. Basler driver

**Comment by Flova** [comment]
I think integrating it into the basler would be fitting as we have a check there either way. But I just had the following idea:

Diagnostic state to tts! We just say (some) if the arbitrary diagnostic states. Therefore the robot tells us if the camera is overheating, the cap is on there or if the motors are stale/overloaded.

**Pull request merged**
