### PR TITLE
Fix/dynup back better

### PR DESCRIPTION
**Pull request by JanNiklasFeld**
# Summary

## Checklist

- [ ] Run `colcon build`
- [ ] Write documentation
- [ ] Test on your machine
- [ ] Test on the robot
- [ ] Create issues for future work
- [x] Triage this PR and label it

### CODE REVIEW

**Comment by jaagut** [comment]
@JanNiklasFeld What/why did you change the spline in the engine?

**Comment by Flova** [comment]
> @JanNiklasFeld What/why did you change the spline in the engine?

I think it moves the head at a different point, resulting in less head injuries.

**Comment by JanNiklasFeld** [comment]
> > @JanNiklasFeld What/why did you change the spline in the engine?
> 
> I think it moves the head at a different point, resulting in less head injuries.

Yes, that was the reason.

**Comment by Flova** [comment]
We now solved the standing up issues

**Pull request closed without merging**
